### PR TITLE
AB special actions screen updates

### PR DESCRIPTION
**Pull request by aliciabillings-noaa**
I think I did this right?

### CODE REVIEW

**Comment by jimfellows-NOAA** [comment]
Sorry I didn't get around to this last week.  Looks good for starters, I think I need to modify my SQLite DB to insert action type / species sampling plan "location" to make the pyrosome feature work correctly?  Taking a look at that this morning.

The only comment I have so far is related to changes in the FishSampling.py.  The SpeciesSamplingPlanLu.get() method returns an instance of SpeciesSamplingPlanLu, and if you look at how that object is defined in TrawlBackdeckDB_model.py, I think SpeciesSamplingPlanLu.get().species_sampling_plan should return the database integer value.  Need to see if both .species_sampling_plan and .species_sampling_plan_id return the same value, but I think that's why its originally written that way.

```
class SpeciesSamplingPlanLu(BaseModel):
    count = IntegerField(db_column='COUNT', null=True)
    count_type = IntegerField(db_column='COUNT_TYPE_ID', null=True)
    display_name = TextField(db_column='DISPLAY_NAME', null=True)
    parent_species_sampling_plan = ForeignKeyField(db_column='PARENT_SPECIES_SAMPLING_PLAN_ID', null=True, model='self', to_field='species_sampling_plan')
    plan_name = TextField(db_column='PLAN_NAME', null=True)
    principal_investigator = ForeignKeyField(db_column='PRINCIPAL_INVESTIGATOR_ID', null=True, model=PrincipalInvestigatorLu, to_field='principal_investigator')
    protocol = ForeignKeyField(db_column='PROTOCOL_ID', null=True, model=ProtocolLu, to_field='protocol')
    species_sampling_plan = PrimaryKeyField(db_column='SPECIES_SAMPLING_PLAN_ID')
    stratum = ForeignKeyField(db_column='STRATUM_ID', null=True, model=StratumLu, to_field='stratum')
    taxonomy = ForeignKeyField(db_column='TAXONOMY_ID', null=True, model=TaxonomyLu, to_field='taxonomy')
```

**Comment by jimfellows-NOAA** [comment]
Yea I'm still trying to understand what's going on with SpeciesSamplingPlanLu.  Your change using "species_sampling_plan_id" is also working for me... there have been a few instances with the survey apps where there are issues in the main code base that seem very suspect, which makes me worried that the working build that Todd or Will created last has tweaks that we aren't aware of and were never checked into the code,  or its using different versions of libraries.  So even building from the master branch now might result in some different behavior.  If we continue down the route of rebuilding with code changes, we'll have to really make sure that data is going where its supposed to.

Everything looks great though, the new location protocol appears to be functioning and inserting into Specimens correctly as does the lamprey scar photo option.

**Comment by aliciabillings-noaa** [comment]
Good! I'm glad it works on your machine too.

I'll go through some common and uncommon scenarios tonight and see if I can
break anything.

--
Alicia Billings (she/her)
Fishery Biologist
NOAA/NMFS/NWFSC/FRAM/FEAT
2032 Marine Science Drive
Newport, OR 97365
541.867.0507

**Comment by jimfellows-NOAA** [comment]
Thinking it'd be good to get the new trawl backdeck build into the hands of the survey team to actually test to make sure it makes sense to them.  Not sure if that's Victor or someone else, but was thinking I can merge and pitch that to the group.  We could always go over some examples in the thursday meeting, but might be good to get that ball rolling sooner.

I think the changeLoc function in SpecialActionsScreen.qml needs to be adjusted slightly so the argument is passed to setProperty:

Existing code:
```
function changeLoc(location) {
        tvSamples.selection.forEach (
            function(rowIndex) {
                tvSamples.model.setProperty(rowIndex, "value", value)
                var item = tvSamples.model.get(rowIndex)
                if (location === null) {
                    specialActions.delete_specimen(item["specimenId"])
                    console.info('trying to delete')
                } else {
                    specialActions.upsert_specimen(rowIndex)
                    console.info("upserting")
                }
            }
        )
    }
```

New code (note change to variable passed to setProperty):
```
function changeLoc(location) {
        tvSamples.selection.forEach (
            function(rowIndex) {
                tvSamples.model.setProperty(rowIndex, "value", location)
                var item = tvSamples.model.get(rowIndex)
                if (location === null) {
                    specialActions.delete_specimen(item["specimenId"])
                    console.info('trying to delete')
                } else {
                    specialActions.upsert_specimen(rowIndex)
                    console.info("upserting")
                }
            }
        )
    }
```

**Comment by jimfellows-NOAA** [comment]
I don't expect any testing issues, but going to build off this branch and leave it unmerged for now just incase.

**Comment by aliciabillings-noaa** [comment]
Well, may have found one of those instances with tweaks you were talking about. The sound that should be heard when they take a basket weight is not working. There is a warning when I run it from PyCharm on my computer that I didn't notice before:

`WARNING:FramUtil.py:116:[Qt]qrc:/qml/trawl/WeighBasketsScreen.qml:71  :71: TypeError: Property 'play_sound' of object SoundPlayer(0x25a9fab4df0) is not a function`

Any ideas?

**Comment by jimfellows-NOAA** [comment]
Ahhh I've definitely seen that error before, I think this came up when Sara and I were first working on this.  Its another one of those things where the code has a pretty obvious bug, and I bet that Todd fixed it, but it maybe never made it onto the master branch of the code.

I get the homer simpson donuts sound when I change the name of the function to the pyQtSlot name and explicitly pass all arguments, optional or not:
```python
function checkSubsampleCount() {
        var soundPlayed = false
        console.info("CHECKING SUBSAMPLE, SOUND??????")
        if (tfSubsampleFrequency.text) {
            var diff = tvBaskets.model.count - weighBaskets.lastSubsampleBasket
            if (diff >= parseInt(tfSubsampleFrequency.text)) {
                soundPlayer.playSound("takeSubsample", 0, false)
                soundPlayed = true
                dlgConfirm.show("to take a subsample", "take subsample")
            }
        }
        if (!soundPlayed) {
            soundPlayer.playSound("takeWeight", 0, false)
        }
    }
```

**Comment by aliciabillings-noaa** [comment]
Great! I'm glad it was something easy. I saw that last night and thought that may be the case, but I was having issues getting the changes to show up when I reran and I didn't have time to deal with it. QML and I don't get along...

So you'll have to rebuild to push that change through, right? We should have the group decide if they want two or three buttons for the pyrosome location at the meeting today. Victor said he didn't think having three was a bad thing, but Aaron wanted two, so I'd like them to make the decision. If they want the change I can jump in and update the code there as well before your rebuild.

**Comment by jimfellows-NOAA** [comment]
Probably overkill but created an issue for the bug just for fun.  Looked around the code for other references to "play_sound", but that was the only one, so I think this fix should be pretty straight forward.  I can rebuild after our meeting today depending on how things go.

**Comment by aliciabillings-noaa** [comment]
Not sure if you rebuilt after fixing the bug yet, but I went a head and updated the button names for the pyrosome project based on what Aaron said at the meeting.

**Comment by jimfellows-NOAA** [comment]
Perfect, thank you!  Hadn't done anything yet, I'll rebuild with the latest and greatest soon and have something ready to test when I get down tomorrow.

**Comment by montsaroffNoaa** [comment]
Closing after consult with Jim, changes have been added.

**Pull request closed without merging**
